# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "nuget" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    groups:
      Avalonia:
        patterns:
          - "*Avalonia*"
          - "Dock.Model.Mvvm"
      SixLabors:
        patterns:
          - "SixLabors*"
    ignore:
    - dependency-name: "Avalonia.Controls.TreeDataGrid"
      # Versions starting at 11.2.0 are commercial for a lack of open source contributors/maintainers.
      versions: [ ">=11.2.0" ]

